### PR TITLE
feat: add --watch flag

### PR DESCRIPTION
**Pull request by aleclarson**
You must install `uvu-watch` globally to use it.

### CODE REVIEW

**Comment by lukeed** [comment]
Hi, thank you, but I mentioned a number of times that something like this is not wanted:

* https://github.com/lukeed/uvu/commit/941a652436376bb25ec562fa5ee5b726ced64a5e
* https://github.com/lukeed/uvu/issues/17#issuecomment-657733688
* https://github.com/lukeed/uvu/issues/17#issuecomment-800579843
* https://github.com/lukeed/uvu/issues/17#issuecomment-801355978

`uvu` is meant to **run tests** – it's something else's concern to worry about watching the file-system.

As soon as a watcher is added (even if external) it's begging for a whole suite of new issues/feature-requests (like #36). Much rather do one thing well – and it's already been proven that uvu can work _well_ with any number of existing file watcher binaries that a user may have.

I'd welcome a PR for adding `uvu-watch` or a `filespy`-based CLI to the examples and/or docs though.

Hope you understand.

**Comment by aleclarson** [comment]
> `uvu` is meant to **run tests** – it's something else's concern to worry about watching the file-system.

Correct, that would be `uvu-watch`'s concern. :)

> begging for a whole suite of new issues/feature-requests

If those requests are worth adding to `uvu-watch`, I'll consider it.

But `uvu` is fast enough that it's really not necessary, and it's not hard to explain that to people.

> it's already been proven that uvu can work _well_ with any number of existing file watcher binaries that a user may have.

You can still use `uvu` with those binaries. Nothing stopping you.

But nothing can compare to adding `--watch` or `-w` to the end of your `yarn test` command. 
You can skip adding a separate script for watch mode like `"test:dev": "watchlist src tests -- npm test"`.

For new users, it's nice to have `uvu` suggest `uvu-watch` when they naïvely try using the `--watch` flag before ever installing `uvu-watch` or searching the issues for a solution. What I mean is, it's more discoverable to new users.

> I'd welcome a PR for adding `uvu-watch` or a `filespy`-based CLI to the examples and/or docs though.

This brings me to my final point. This PR makes `uvu-watch` the perfect solution (as opposed to using `uvu-watch` without this PR). Let me explain. If you install `uvu-watch` globally, it won't be installed by CI (which would slow it down). If you use `uvu-watch` globally without this PR, you have to use `uvu` instead of `yarn test`, which means you're forced to specify the same arguments in your `yarn test` script (a bad DX). And again, if you install `uvu-watch` locally, you slow down CI. Thus, having the local `uvu` invoke the global `uvu-watch` is the perfect solution.

Btw, `uvu-watch` *always* uses the local `uvu`. It complains if you don't have `uvu` installed locally.

**Comment by lukeed** [comment]
Yes thank you. I understand your perspective and your points, but I simply do not want to add this, not even a flag (that makes it _seem_ like it will watch files) that forwards responsibility to something else.

I know we will disagree but it does not belong.

I'm sorry you spent time on this, but you missed/overlooked the times I had already given my stance on the subject. And I wish you had said something before starting work.

Luckily, though, I don't think your uvu-watch work has gone to waste. It can still be used even if it just needs a couple modifications

**Comment by aleclarson** [comment]
To be clear, I know you're not an irrational person, so it seems like you're holding back part of your rationale here.

- better DX for users
- 10 eLOC of maintenance burden
- zero downsides for those who don't want to use it

Is it a security concern? (I can give you sole NPM publishing rights)

Is it some kind of principle against optional dependencies?

Forgive the accusation, but could it be an emotional thing?

I won't badger you anymore if I'm ticking you off. 😆

**Comment by lukeed** [comment]
All good!

It's as simple as me having decided (a while ago) that watching the filesystem is out of scope for the project. It's _not_ what a test runner is, by my definition. And including the changes here to emit/forward the responsibility to something else is not an elegant solution IMO – and by association, it makes file-watching _kinda sorta_ part of uvu's scope.

But ultimately it comes down to falling out of scope & to having simpler and more elegant solutions (imo) documented already.

You may have been able to convince me a few months ago when I was in the process of deciding a stance 😅 but that ship has sailed and I'm very happy with the end result.

**Comment by aleclarson** [comment]
I'm not one to let past decisions dictate future decisions, so I guess we're at philosophical odds here.

I've given better arguments above already, but I may as well mention that all other popular test runners have a `--watch` flag. We can have our cake and eat it too (ie: have a `--watch` flag, but delegate its behavior to avoid over-complicating `uvu` core). I'd push you to reconsider the idea that delegation is comparable to direct implementation in terms of project scope (for one, I could handle all issues related to the `--watch` flag if you wanted).

> simpler and more elegant solutions

I contend this is objectively false, but I've already stated my reasons why, so that's that. :)

**Comment by lukeed** [comment]
It's a past and current decision. Nothing presented is new here and I've already weighed through it.

Also, I don't want to be other test runners. Or I'd have just continued using them. File-watching is _associated with_ testing, but not a core requirement. If it were impossible to attach file-watching ability to current uvu, then obviously I would have made a different decision. But, it's possible, and it works well without adding _anything_ to uvu.

Again, I'm sorry, but we don't have to agree.

**Comment by aleclarson** [comment]
Did you think it was possible to add `--watch` flag in **10 eLOC**, though? ;)

For clarity, here's a list of what makes this PR the best approach:
- runs tests immediately, then watches
- `--watch` flag is easily discoverable (in `--help` output & expected by newcomers)
- no extra `yarn test:watch` script, just do `yarn test -w`
- [Watchman](https://facebook.github.io/watchman/) support
- delegates to globally-installed package
- parity with other solutions
  - local `uvu` must be installed
  - file-watching not maintained in `uvu` core
  - no downsides if you prefer another watcher binary
  - CI duration is unaffected
  - debouncing
 
Such benefits are proof this approach is the simplest and most elegant, and should thus be merged. 

I rest my case! ✌️

**Comment by lukeed** [comment]
It's possible to be less than 10. It's not about LoC.

As I said, multiple times, it is out of scope. You are not presenting any new arguments & at this point I think you may be intentionally disregarding my comments in the hopes of furthering your own project. Perhaps the last bit is incorrect -- I've been giving you the benefit of the doubt because I like you, your work, and I know you contribute to many projects purely for the sake of contribution -- but I have been very clear: this is out of scope & does not fall into my definition of what a "test runner" must have.

Pairing up with a sibling binary Is that perfectly acceptable solution & in my opinion, is the preferred solution. It yields the most flexibility and compatibility for users' preferences. Like yours, it relies on a global install of something that would not affect CI or any other environments. The only "drawback" Is that you need an extra npm script... which is a non-issue considering most real-world projects already have at least 8 scripts.

Lastly, only in Node.js is it "uncommon" to pipe and chain binaries together. This is the same ecosystem that is (only recently) complaining about tools getting too big and/or trying to solve too much.

A test runner runs tests. That's it.

**Comment by aleclarson** [comment]
> It's possible to be less than 10. It's not about LoC.

Sure, but it would be less readable, IMO. 😅 
Spawning `npx` is a pretty elegant way of delegating responsibility to a global package, if you ask me. :)
I had an a-ha moment with that one. lol

> You are not presenting any new arguments

I know. That last comment was a summary for easier consideration. :D

> intentionally disregarding my comments in the hopes of furthering your own project

Nope, I truly believe this PR is the best solution. Which point of yours did I ignore?

I don't think I can convince you that "out of scope" is addressed by delegation, but it is. :P

> Pairing up with a sibling binary is a perfectly acceptable solution

Sure, but this PR and that are *not* mutually exclusive. We can have best of both worlds!

> only "drawback" is that you need an extra npm script

You may have missed the 3 other benefits not provided by current solutions:

> * runs tests immediately, then watches
> * `--watch` flag is easily discoverable (in `--help` output & expected by newcomers)
> * [Watchman](https://facebook.github.io/watchman/) support

But I'm sure you didn't intend to act hypocritically by ignoring those and then claiming I'm ignoring your points. I'm more charitable than that, and I just assume you're just tired of explaining yourself to me. 😆

**Comment by lukeed** [comment]
> I just assume you're just tired of explaining yourself to me.

Yes this conversation has been circular for a while now.

**Comment by aleclarson** [comment]
I've updated `uvu-watch` to install `filespy` on-demand, so it can be used locally without slowing down CI. 🎉 

Where should I mention it in `docs/watch.md`? 

Is at the top okay? My reasoning is that `yarn add uvu-watch -D && yarn test -w` is the easiest way to get going. :)

**Comment by curtgrimes** [comment]
FWIW, I was disappointed today to find that `--watch` did not do anything when I tried it on a whim on uvu.

**Pull request closed without merging**
