### PR TITLE
fix: 🧪 Replace any with more refined types

### PR DESCRIPTION
**Pull request by Beraliv**
## Goal

Hey @lukeed! It took me some time to create a draft.

Please let me know if you'd like to see dependencies like `typescript` and `ts-essentials` (I don't insist but some utilities may be handy but I will leave it up to you)

Related to #169

## Summary

- Added `typescript@^4.5` as `devDependency` to be able to run type tests
- Added `ts-essentials` as `devDependency` to use `DeepPartial` e.g. for `equal` (TBC)
- TBC (it's still in progress)

Apologies for 

## Planned

- Replace types for `ok`, `equal`, `type`, `instance`, `not`
- Added type tests for all changed declarations

### CODE REVIEW

**Comment by lukeed** [comment]
Hi there, there is zero reason to add typescript (or essentials) as a depending here. At best, they’d be devDependencies, but still I don’t even see need for them there either. A “dependency” means everyone will forcibly download it at installation because X is needed at runtime.

**Comment by lukeed** [comment]
The ArrayOrSingle type is exactly what I have already. Please remove, pointless change

**Comment by Beraliv** [comment]
@lukeed hey! Thanks for a quick response!

> there is zero reason to add typescript (or essentials) as a depending here. At best, they’d be devDependencies, but still I don’t even see need for them there either

I agree with you. I'm planning to add type tests to make sure there are no regressions, therefore you would need `typescript` to be listed as `devDependency`.

> The `ArrayOrSingle` type is exactly what I have already. Please remove, pointless change

No problem, addressed it in https://github.com/lukeed/uvu/pull/243/commits/abeebd189c5eac0fcafe74bf51ecc00ddc24e90c

**Comment by Beraliv** [comment]
I decided to close the PR due to my other priorities

**Pull request closed without merging**
