### PR TITLE
Add puppeteer example

### LINKED ISSUE #75: Proposal: Add example for Uvu + Puppeteer
Today I got a really fun setup working: Uvu (0.5.0 using native ES module support) for writing and running tests and assertions, and Puppeteer for evaluating code in the browser during a test.

```js
MySuite('can fetch data!', async ({ page }) => {
  const fetchedData = await page.evaluate(async () => {
    const result = await fetch('https://httpbin.org/get')
    return await result.json()
  })

  assert.ok(fetchedData)
})
```

I'm enjoying how minimalist it is—I can bundle my code however I want and build my app however I want. When it's time to test, I just need to spin up the app's development server, then I'm free to use Uvu and Puppeteer to visit pages and run test code.

@lukeed I can pull request an example setup if that's fine by you?

There's more than one way to make this work, but `before` and `after` hooks probably are best for most cases:

```js
import puppeteer from 'puppeteer-core'

MySuite.before(async context => {
  const browser = await puppeteer.launch(),
        page = await browser.newPage()

  context.browser = browser
  context.page = page
})

MySuite.after(async ({ browser }) => {
  await browser.close()
})
```

### PR DESCRIPTION
**Pull request by AlexVipond**
Closes #75

### CODE REVIEW

**Comment by lukeed** [comment]
Thanks! I pushed minor changes – mostly related to code style.

Can you think of an easy way to run tests using code from `/src` directory (eg, the basic `maths` stuff in other examples)? If not, no worries. This can land as is.

**Comment by lukeed** [comment]
Looks good to me! Will wait for you to 👍 my slight refactoring & the readme notes. 
Refactor was only to make it more like the existing examples (individual suites + individual hook functions).

Thanks a lot!

**Comment by AlexVipond** [comment]
Yep, the refactor and readme look great!

**Comment by lukeed** [comment]
Thanks!

**Comment by lukeed** [comment]
Hey, I updated the example so that `sirv-cli` is used for the server instead of `vite`: 43d100b 
AKA, follow-up to [this](https://twitter.com/lukeed05/status/1333616049015513089) :)

**Comment by AlexVipond** [comment]
👍 👍 🚀

**Pull request merged**
