### PR TITLE
Try-Catch dynamic import and fallback to require (fixes typescript example)

### LINKED ISSUE #72: ESM – TypeError [ERR_UNKNOWN_FILE_EXTENSION]
I get this error when trying the typescript example with updated dependencies:
```diff
TypeError [ERR_UNKNOWN_FILE_EXTENSION]:
    Unknown file extension ".ts" for /home/tolu/github/uvu/examples/typescript/tests/math.ts
```

An image for context 😄 

image

Single tests files can be run via:
```
node --loader ts-node/esm test/math.ts
```

### PR DESCRIPTION
**Pull request by tolu**
> First off @lukeed, lots of thanks and ❤️ for this fantastic framework and everything else you do for the js community 🙌 🙇 

## Issue

The [typescript example](./examples/typescript) currently throws a TypeError `ERR_UNKNOWN_FILE_EXTENSION` since the dynamic import "default" does not support '*.ts'-files.

See details about the thrown error in #72 and the status of ESM-support in ts-node here https://github.com/TypeStrong/ts-node/issues/1007

As @cspotcode has [pointed out][issue-comment], single test files run fine using `ts-node/esm` like so:
```
node --loader ts-node/esm test/math.ts
```

### Alternative 0 (this PR)

As per @cspotcode's [suggestion][pr-comment]:
> Another option is for uvu to detect ERR_UNKNOWN_FILE_EXTENSION and fallback to require.resolve() / require(). This way you attempt loading via ESM loaders, including ts-node's own ESM loader if the user has decided to use it. If that doesn't work, you fallback to require(), which will invoke any require() hooks that might be installed.
> 
> node --loader ts-node/esm will avoid this error.

### Alternative 1

Provide an extra option to be able to opt-out of the `esm-loader` like so:

```ts
sade('uvu [dir] [pattern]')
  .version(pkg.version)
  // ...
  .option('-e, --esm', 'Enable esm-loader', true)
  .action(async (dir, pattern, opts) => {
    try {
      if (opts.color) process.env.FORCE_COLOR = '1';
      let { suites } = await parse(dir, pattern, opts);

      if (hasImport && opts.esm) {
          // ...
      }
    }
  })
```

### Alternative 2

Check for `ts`-files among suites and the use of `ts-node`. More automatic but... I dont know...

```ts
// bin.js

// esm loader does not work for *.ts files
const suitesContainTypescript = suites.filter(s => /tsx?$/.test(s.name)).length > 0;
const usesTsNodeRegister = [].concat(opts.require || []).includes('ts-node/register');
const canUseImport = !suitesContainTypescript && !usesTsNodeRegister;

if (hasImport && canUseImport) {
  await dimport('uvu/run').then(m => m.run(suites, opts));
}
```

closes #72 
related to #69 #64 

[pr-comment]: https://github.com/lukeed/uvu/pull/73#issuecomment-735421094
[issue-comment]: https://github.com/lukeed/uvu/issues/72#issuecomment-735420714
[luke-comment]: https://github.com/lukeed/uvu/issues/72#issuecomment-735872025

### CODE REVIEW

**Comment by tolu** [comment]
I feel I'm leaning towards alternative 2 here and writing that out explicitly in the typescript example...

```json
{
  "script": {
    "test": "uvu -r ts-node/register -e false tests"
  }
}
```

**Comment by cspotcode** [comment]
Another option is for `uvu` to detect `ERR_UNKNOWN_FILE_EXTENSION` and fallback to `require.resolve()` / `require()`.  This way you attempt loading via ESM loaders, including `ts-node`'s own ESM loader if the user has decided to use it.  If that doesn't work, you fallback to `require()`, which will invoke any `require()` hooks that might be installed.

`node --loader ts-node/esm` will avoid this error.

**Comment by tolu** [comment]
@cspotcode a much neater solution, I'll update the PR 👍

**Comment by lukeed** [comment]
Appreciate both of your efforts & attention on this over the weekend 🙇 Left my comments in #73 since more of the convo was there.

**Comment by cspotcode** [comment]
I think I actually had my suggestion backwards.  The idea is still mostly the same, but it's actually better to attempt `require()` before `import()`, not the other way around.

You attempt to `require()` first, checking for a well-known error to be thrown, which node uses to tell you the file should be loaded as ESM.  If you get that error, you attempt a dynamic `await import()`.

Mocha is doing exactly what I described above.  To make `ts-node` compatible, we had to make sure we throw an identical-looking error.

Here is mocha's implementation, which is pretty simple:
https://github.com/mochajs/mocha/blob/master/lib/esm-utils.js#L15-L27

**Comment by benmccann** [comment]
This PR should be rebased (assuming it's still helpful after https://github.com/lukeed/uvu/issues/72#issuecomment-736708123)

**Comment by lukeed** [comment]
Looks like I forgot to close this when closing #72 – via https://github.com/lukeed/uvu/issues/72#issuecomment-785284737 
Still haven't seen any issues related to this come up since the `0.5.1` release 🤞 

Thanks again!

**Pull request closed without merging**
