### PR TITLE
Connect `actual` and `expects` types in `equal()` and `is()`

### PR DESCRIPTION
**Pull request by ai**
This changes will improve TypeScript support:

1. User will have autocomplete in tests:

Captura desde 2023-09-06 15-12-54

2. Refactoring will be a little easier since test will help you guide what types you need to update (refactoring will be a little faster).

Captura desde 2023-09-06 15-13-18

### CODE REVIEW

**Review by lukeed — COMMENTED** [review]
Thanks :) Can you leave these as inline function declarations tho

**Comment by ai** [comment]
> Can you leave these as inline function declarations tho

Sure. It will not cover all cases, but we could start from simpler version.

**Comment by lukeed** [comment]
Why won’t it cover? You can do the same with the `is.not` & `not.equals` definitions too. I just didn’t want to add a new interface

**Comment by ai** [comment]
> You can still overload the function definitions. I just didn’t want to add a new interface

Got it! Pushed.

**Comment by JaKXz** [comment]
This is a cool change :) just curious, is a release planned to include this?

**Pull request merged**
