### PR TITLE
add pta and zora to the benchmark

### PR DESCRIPTION
**Pull request by lorenzofox3**
Hi,

I think your benchmark is not very relevant as a bit contrived. In my opinion, real use cases are closer to non blocking asynchronous code spread into multiple files. That is where you will see a difference anyway, especially for runners which use parallelization. You can have an example in [my repository](https://github.com/lorenzofox3/zora).

### CODE REVIEW

**Comment by lukeed** [comment]
Hey,

I've mentioned a few times that the benchmark is purposefully simple and is meant to record startup metrics primarily. Of course a simple test suite doesn't _actually_ measure real-world test cases. I've stated that there will be a full, real-world benchmark that all candidates will use, and it will allow things like parallelization to shine. Yours is equally flawed/useless by the way, but I think you know that.

I did not include `zora` initially because it's not a test **runner** – it's a test framework, but there's no CLI runner. I actually didn't know `pta` existed until this PR, so thanks for showing me! 

That said, please remove `zora` from the PR. It's not on equal footing with the other candidates.
Equally, I could have run `node suites/uvu` for an even greater difference, but it'd be a lie because it skips/bypasses the CLI stage which the others cannot do.

I'm happy to include `pta` since it _does_ include the CLI aspect. I can label it as `zota/pta` if you'd like – up to you.

Thanks~!

**Comment by lorenzofox3** [comment]
> Hey,
> 
> I've mentioned a few times that the benchmark is purposefully simple and is meant to record startup metrics primarily. Of course a simple test suite doesn't _actually_ measure real-world test cases.

Sorry I was not aware of these statements, I landed here from another repository and this communication does not seem to be available in this repository

> I've stated that there will be a full, real-world benchmark that all candidates will use, and it will allow things like parallelization to shine.

Cool. So you should probably simply discard this pull request which may not be relevant anymore in the perspective of the coming benchmark

> Your benchmark is equally flawed/useless by the way, but I think you know that. 

On the contrary I find it matches pretty well my dev experience with mocha and jest at work, and with zora and pta for fun. I would be very appreciative if you could enlighten me on how my benchmark is flawed/useless and how I could improve it.

> I did not include `zora` initially because it's not a test **runner** – it's a test framework, but there's no CLI runner. I actually didn't know `pta` existed until this PR, so thanks for showing me!
> That said, please remove `zora` from the PR. It's not on equal footing with the other candidates.

On that side, I think your benchmark can't treat any of the candidate on equal footing as some manage to load ES files others do not, some spawn child processes others do not, running a one file suite is different than matching a glob pattern and can make a huge difference even if you want to measure the *startup time* only.

Zora is not a test runner per se.. and that is the beauty of it: you don't even need a test runner ! If you define a test runner by its ability to run a test suite you can simply run 

``echo "process.exit(0)" | node -r ./suites/zora/*.js`` (how whatever glob)

Congratulations, you have just built a test runner ! Now, your CLI can be whatever npm script or bash you want (which will have the exact same output than tape, member of the candidates club :) )

You can even use tape to run a zora program !

``tape ./suites/zora/*.js`` 

:)

> Equally, I could have run `node suites/uvu` for an even greater difference, but it'd be a lie because it skips/bypasses the CLI stage which the others cannot do.

I don't see how it would be a lie if the idea is to benchmark the dev experience. The CLI stage is probably the lowest cost in the testing process.

> I'm happy to include `pta` since it _does_ include the CLI aspect. I can label it as `zora/pta` if you'd like – up to you.

Just pta is fine. But as I said earlier, does it matter if you are going to throw the benchmark for a better one ?

> Thanks~!

You are welcome, I am happy to see coming newcomers in the *testing scene* ! You should also have a look at [baretest](https://github.com/volument/baretest) which seems to be aligned with the goals of your project

**Comment by lukeed** [comment]
> Sorry I was not aware of these statements

Not to worry; not expecting everyone to follow all threads! Just wanted to highlight that I'm aware of the shortcomings – as every/any benchmark is faced with the same "this is incomplete..." argument. It's _something_ & something _specific_ – not an end-all analysis.

> which may not be relevant anymore

I will be keeping this benchmark alongside the new one. Again, this one is primarily indicating startup/boot time for an overly simplified test suite. In other words, it's measuring overhead. Granted, this cost is only paid once (unless your multi-processing implementation is problematic). The second benchmark will be a considerably larger test setup, spanning multiple files and suites per file. it will be more representative since any MPs can invoke their MP, the CLI/startup cost becomes comparatively insignificant, and it just becomes a matter of "how fast can X execute N tests, comprising a mixture of async tests"

> if you could enlighten me on how my benchmark is flawed

Just like mine, you run a low, insignificant number of tests. I have 3 tests for 12 assertions. You have 10 tests for 10 assertions. The size of both are meaningless / too low to be representative – so you're also only _really_ measuring startup/process execution time.

(Also, the [`zora` test case](https://github.com/lorenzofox3/zora/blob/master/benchmarks/zora/index.js#L2) is the only candidate that requires itself _before_ the loop. This only affects `zora` and `tape` – but both should have a `require` at the top of `test1.js` file. Otherwise, `tape` is the only one penalized for the ever-so-slight cost of relying on require cache.)

For both of us, our benchmarks _are_ representative of real-world improvements. For my work specifically, I can have 25 tests finish in 3ms or 160 tests finish in 6ms. Your numbers will be similar, assuming the test handlers/code themselves are quick. We'll both finish our test suite(s) while the others are still booting & getting ready to do anything. 

But this won't satisfy developers working on enormous code bases with ~10k tests. So we need something bigger.
I'm hoping the 2nd benchmark will have at least a thousand tests. I just have to think of a way to make them indicative of massive project suites w/o losing my mind & writing them by hand.

> I think your benchmark can't treat any of the candidate on equal footing

I'm not comparing feature sets.
I'm comparing equal component/architecture.

Put differently, I can't compare a HTTP _router_ (aka, _just_ the matching logic) against a HTTP framework (aka, the router _plus_ the request/response engine). They're fundamentally different, because 1 is missing a core component of the other, which definitionally makes them different.

In true examples, my `trouter` (a router) can handle ~2M req/s. And then Polka (a web framework on top of `trouter`), can only handle 50k req/s. It's not because Polka sucks or is slow – it's because it's relying on the `http` engine to actually run and pass/reply to requests.

Back to testing: all candidates must be _test runners_ – they must have the ability to execute tests (obviously), but they must have a CLI component that can _actually run_ your tests.

For your numbers, executing this `zora` test suite is ~70ms – that's through `node suites/zora`. Obviously that works, but there's no "runner" aspect, so you run into a void once you have a second test file. Presumably that's why you created `pta`, which fills this void. 

Now you have a _test runner_.
Back to numbers, the `pta` suite completes in ~180ms, which is not a bad score at all.
This also doesn't mean `pta` is slow – but it does show that there's _some_ overhead – probably more than you were expecting? Does it matter: probably not. But again, this benchmark is measuring the total process execution time (for test runners) on a simple test suite.

> I don't see how it would be a lie

Because it'd be cutting out half of what's being done. 
There's zero way to `node suites/jest` or `node suites/ava` or `node suites/ava` – so they'd be penalized for being forced to do `fs` reads, pattern-match, etc - whereas `zora` (and `uvu`) can take a shortcut and execute the file directly.

Yes, it's _good_ that we both designed that ability into our tools, but if we're going to measure against the "big names" we have to give no reason for "unfair" play.

Again, I refer you to my Trouter-vs-Polka example.
While `trouter` is certainly a HTTP router, I can't include it in a benchmark with HTTP frameworks.

> I am happy to see coming newcomers

Thanks! I've only heard good things about `zora` :) A few of my friends are using it and will likely keep using it :D

**Comment by lorenzofox3** [comment]
> > Sorry I was not aware of these statements
> 
> Not to worry; not expecting everyone to follow all threads! Just wanted to highlight that I'm aware of the shortcomings – as every/any benchmark is faced with the same "this is incomplete..." argument. It's _something_ & something _specific_ – not an end-all analysis.
> 
> > which may not be relevant anymore
> 
> I will be keeping this benchmark alongside the new one. Again, this one is primarily indicating startup/boot time for an overly simplified test suite. In other words, it's measuring overhead. Granted, this cost is only paid once (unless your multi-processing implementation is problematic). The second benchmark will be a considerably larger test setup, spanning multiple files and suites per file. it will be more representative since any MPs can invoke their MP, the CLI/startup cost becomes comparatively insignificant, and it just becomes a matter of "how fast can X execute N tests, comprising a mixture of async tests"
> 

That was my point. I don't see how relevant this can be and what information it gives you: In the same way that you will  probably not measure boot time to assess database performances, what is the value of measuring *boot time* of a test framework ? Especially if some rely on heavier set up (spawning child processes) to make them run the actual tests (the purpose they were built for) faster. On the contrary, I will be quite interested in the second benchmark which seems closer to the way a dev actually uses a test runner.

> > if you could enlighten me on how my benchmark is flawed
> 
> Just like mine, you run a low, insignificant number of tests. I have 3 tests for 12 assertions. You have 10 tests for 10 assertions. The size of both are meaningless / too low to be representative – so you're also only _really_ measuring startup/process execution time.
> 

I am not sure you have read properly the readme. What you have seen is the latest "profile" generated but you can create any profile with the [provided script](https://github.com/lorenzofox3/zora/blob/master/scripts/generate.js). If you are interested in *huge* test suites for example (200 files with 10 tests in each ~ 2000 tests - each test waiting 20ms for any I/O task to complete) I get the following numbers on my machine:

| mocha(serie) | tape | uvu | mocha(parallel) | jest | ava | zora | pta  |
|--------------|------|-----|-----------------|------|-----|------|------|
| 48s          | 48s  | 47s | 8s              | 13s  | 18s | 0.4s | 0.9s |


> (Also, the [`zora` test case](https://github.com/lorenzofox3/zora/blob/master/benchmarks/zora/index.js#L2) is the only candidate that requires itself _before_ the loop. This only affects `zora` and `tape` – but both should have a `require` at the top of `test1.js` file. Otherwise, `tape` is the only one penalized for the ever-so-slight cost of relying on require cache.)
> 

It has not always been the case: it is just to be able to run the same test suite with zora and pta. And trust me, the cost of requiring a cached node module is not even noticeable. Most of the difference will come from the ability of a runner to run the tests concurrently.

I think the weakness of my benchmark is the "test code" which is not blocking at all and consumes very little resources. In practice a lot of Javascript code is not blocking, delegating I/O work to other processes (databases, etc). However, these other processes consumes more resources than a simple ``setTimeout``.  That is why I was particularly interested in your suggestions

> For both of us, our benchmarks _are_ representative of real-world improvements. For my work specifically, I can have 25 tests finish in 3ms or 160 tests finish in 6ms. Your numbers will be similar, assuming the test handlers/code themselves are quick. We'll both finish our test suite(s) while the others are still booting & getting ready to do anything.
> 
> But this won't satisfy developers working on enormous code bases with ~10k tests. So we need something bigger.
> I'm hoping the 2nd benchmark will have at least a thousand tests. I just have to think of a way to make them indicative of massive project suites w/o losing my mind & writing them by hand.
> 
> > I think your benchmark can't treat any of the candidate on equal footing
> 
> I'm not comparing feature sets.
> I'm comparing equal component/architecture.

That can not be the case as they may have totally different architecture. In my opinion you are trying to compare technical details which are not comparable as very different in some cases

> Put differently, I can't compare a HTTP _router_ (aka, _just_ the matching logic) against a HTTP framework (aka, the router _plus_ the request/response engine). They're fundamentally different, because 1 is missing a core component of the other, which definitionally makes them different.
> 

I agree, but in my opinion, your benchmark is trying to asses web framework performances by comparing their routers only. As you say, that may not be relevant as it is far from being the bottleneck anyway. I would rather compare test runners on their ability to run a full test suite rather than on their ability to load a file quickly.

> In true examples, my `trouter` (a router) can handle ~2M req/s. And then Polka (a web framework on top of `trouter`), can only handle 50k req/s. It's not because Polka sucks or is slow – it's because it's relying on the `http` engine to actually run and pass/reply to requests.
> 
> Back to testing: all candidates must be _test runners_ – they must have the ability to execute tests (obviously), but they must have a CLI component that can _actually run_ your tests.

This is a technical detail. You can run a whole test suite with no CLI: zora is a proof. And I believe the fact you need a CLI to run a test suite is a trade off

> For your numbers, executing this `zora` test suite is ~70ms – that's through `node suites/zora`. Obviously that works, but there's no "runner" aspect, so you run into a void once you have a second test file. Presumably that's why you created `pta`, which fills this void.

That is not true. You can run any number of test files (matching any set of glob) with the command provided:

``echo "process.exit(0)" | node -r glob/**/*.js -r need-another-glob/**/*.js`` etc

That is basically what tape does (which you consider to be a *true* test runner), except it does it using 50 lines of js instead of a command line. You don't even need any *entrypoint* like uvu (no ``suite.run()``)

The reasons behind pta is different:  I wanted something specific to node environment which comes with a more opinionated reporter and handle exit codes. 

> Now you have a _test runner_.
> Back to numbers, the `pta` suite completes in ~180ms, which is not a bad score at all.
> This also doesn't mean `pta` is slow – but it does show that there's _some_ overhead – probably more than you were expecting? 

Not really: it uses [esm package](https://www.npmjs.com/package/esm) (which introduces a big overhead) to load ES modules (it was built on node 10) without the need for the user to compile their code first.

>Does it matter: probably not. But again, this benchmark is measuring the total process execution time (for test runners) >on a simple test suite.
> 
> > I don't see how it would be a lie
> 
> Because it'd be cutting out half of what's being done.
> There's zero way to `node suites/jest` or `node suites/ava` or `node suites/ava` – so they'd be penalized for being forced to do `fs` reads, pattern-match, etc - whereas `zora` (and `uvu`) can take a shortcut and execute the file directly.

There is zero way because they took technical decisions and chose some tradeoffs: those impact their boot time but improve their run time (which you can't see with your benchmark). Other framework will take another decision with other benefit/tradeoff. Can't you compare gaz consumption between two cars because one decided to use a thermic engine while the other decided to use an hybrid engine ? 

> Yes, it's _good_ that we both designed that ability into our tools, but if we're going to measure against the "big names" we have to give no reason for "unfair" play.

I don't think it is being unfair. A test runner 's role is to provide a testing experience. If technical details drive the way you use it, it does not mean you will have to use the same way another tool which intend to solve the same problem in a different way. 

> Again, I refer you to my Trouter-vs-Polka example.
> While `trouter` is certainly a HTTP router, I can't include it in a benchmark with HTTP frameworks.
> 
> > I am happy to see coming newcomers
> 
> Thanks! I've only heard good things about `zora` :) A few of my friends are using it and will likely keep using it :D

Don't get me wrong. I am not upset if you don't want to include zora in the benchmark: I just wanted to make sure what I said is understood correctly and correct some *untrue* statements.

Keep me posted, when you decide to set up the *real world* benchmark. I would be very interested in that part :) 

Cheers

**Pull request closed without merging**
